In [1]:
import numpy as np

# Function to compute the rotation matrix and translation vector
def compute_extrinsics(theta_deg, r):
    theta_rad = np.deg2rad(theta_deg)
    R = np.array([
        [np.cos(theta_rad), 0, np.sin(theta_rad)],
        [0, 1, 0],
        [-np.sin(theta_rad), 0, np.cos(theta_rad)]
    ])
    t = np.array([
        [r * np.cos(theta_rad)],
        [0],
        [r * np.sin(theta_rad)]
    ])
    return R, t


# Function to combine rotation matrix and translation vector into a homogeneous extrinsic matrix
def extrinsic_to_homogeneous(R, t):
    homogeneous_matrix = np.eye(4)
    homogeneous_matrix[:3, :3] = R
    homogeneous_matrix[:3, 3] = t.flatten()
    return homogeneous_matrix




In [2]:
# Parameters
num_cameras = 10
angle_step = 360 / num_cameras  # Angle separation between cameras
radius = 1  # Distance from the origin

# Compute extrinsics for all cameras
extrinsics = []
for i in range(num_cameras):
    theta = i * angle_step
    R, t = compute_extrinsics(theta, radius)
    extrinsics.append((R, t))
    
# Display the extrinsics
#extrinsics

# Compute homogeneous extrinsic matrices for all cameras
homogeneous_extrinsics = [extrinsic_to_homogeneous(R, t) for R, t in extrinsics]

# Display the homogeneous extrinsic matrices
homogeneous_extrinsics



[array([[ 1.,  0.,  0.,  1.],
        [ 0.,  1.,  0.,  0.],
        [-0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]),
 array([[ 0.80901699,  0.        ,  0.58778525,  0.80901699],
        [ 0.        ,  1.        ,  0.        ,  0.        ],
        [-0.58778525,  0.        ,  0.80901699,  0.58778525],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[ 0.30901699,  0.        ,  0.95105652,  0.30901699],
        [ 0.        ,  1.        ,  0.        ,  0.        ],
        [-0.95105652,  0.        ,  0.30901699,  0.95105652],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[-0.30901699,  0.        ,  0.95105652, -0.30901699],
        [ 0.        ,  1.        ,  0.        ,  0.        ],
        [-0.95105652,  0.        , -0.30901699,  0.95105652],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[-0.80901699,  0.        ,  0.58778525, -0.80901699],
        [ 0.        ,  1.        ,  0.        ,  0.        ],
    